### ISSUE TITLE
Videos from Uwatchfree are not coming in Show Media

### ISSUE THREAD

**Issue by tushargoyal22** [twosevenxyz/extension-modal#9] opened 2020-12-03 05:59 UTC
Uwatchfree movies, a popular website
https://www.uwatchfree.bz/2020/04/money-heist-2020-season-4-complete/
Video is not visible on Show media on two seven extension on pages of this website

Could you get it working for videos on this website?

**Comment by gurupras** [comment] 2021-12-19 07:01
Closing this issue as everything seems to be working as intended. Feel free to open if you're still facing issues.

**Closed by gurupras** 2021-12-19 07:01 UTC
